### ISSUE TITLE
PWM output linked to temperature makes the octoprint freeze

### ISSUE THREAD

**Issue by bumbalu** [vitormhenrique/OctoPrint-Enclosure#138]
Hi and thank you for most useful plugin!
Issue: 1-5 minutes after print start octoprint server freezes and print stops, Pi remains running. 
Settings: 
Rasp Pi 3B, OctoPrint 1.3.8. Enclosure plugin v. 4.6.
The output gpio is connected to mosfet and runs enclosure ventilation fan. 
Output type is PWM. Link PWM to temparature is YES. All other settings are set and plugin starts functioning well as print starts. 
What I did trying to solve the issue: 
Reinstalled Octopi and enclosure plugin anew. 
Removed all other plugins. 
Removed all other outputs in enclosure plugin. 
I now have solved my problem by setting this output as "temperature control" and "cooler" and it works fine. So I can live with it. But well functioning PWM function is also desirable. 
Thank you.

**Comment by vitormhenrique** [comment]
I need your octoprint log, and print screen for the settings, just to double check...
But I need a log that catches when issue happens, you need to reproduce, save the log, and send it to me...

**Comment by vitormhenrique** [comment]
I can't reproduce the issue, and I even tried on a raspberry pi 1!
Try to use a hardware pwm capable pin, and let me know.
Also, if you reproduce the issue attach the log information here... for now I'm going to close this issue, and we can re-open if needed.

**Comment by vitormhenrique** [comment]
After some research I saw that for some people calling stop and start on PWM too many times causes raspberry pi to freeze, i changed the code to call ChangeDutyCycle instead.
https://github.com/vitormhenrique/OctoPrint-Enclosure/commit/3ac0d62a996a2e9681075db4ac958b9f1770cdb5

**Comment by bumbalu** [comment]
Vitor, after you have changed the code I had one successful print when PWM worked fine and one when it did not turn on at all. But Pi freezing issue is solved. I will do more experiments and report with logs and screenshots if issue repeats. 
Thank you for update!

**Comment by vitormhenrique** [comment]
ok, let me know! it's possible that we might still have some issues, I changed did a little bit of testing but it could be that some specific workflow we could have some issues still... 
but at least you are not freezing your pi and loosing the print anymore, so that's progress...
